name: ccsdev
dependencies:
    - python=3.6.2
    - nose
    - pandas=0.19.2
    - pip: 
        - toolz==0.8.2
        - pyparsing==2.2.0
        - git+https://github.com/jcrudy/clinvoc.git@766927665907eb9c3283cdc4c34f7be04689e14e
